export const ANIMATION_CONTROLS_EVENTS = {
	REQUEST_SAVE: 'ANIMATION_CONTROLS_EVENTS.REQUEST_SAVE',
	REQUEST_DELETE: 'ANIMATION_CONTROLS_EVENTS.REQUEST_DELETE',
	REQUEST_LOAD: 'ANIMATION_CONTROLS_EVENTS.REQUEST_LOAD',
	REQUEST_LOAD_COMPLETE: 'ANIMATION_CONTROLS_EVENTS.REQUEST_LOAD_COMPLETE',
};
