export const GENERAL_EVENTS = {
	REQUEST_PACKAGE_JSON: 'GENERAL_EVENTS.REQUEST_PACKAGE_JSON',
	SEND_PACKAGE_JSON: 'GENERAL_EVENTS.SEND_PACKAGE_JSON',
	SAVE_PNG_SEQUENCES: 'GENERAL_EVENTS.SAVE_PNG_SEQUENCES',
	SAVE_SPRITE_SHEET: 'GENERAL_EVENTS.SAVE_SPRITE_SHEET',
	SAVE_GIF: 'GENERAL_EVENTS.SAVE_GIF',
};
