export const MENU_EVENTS = {
	HELP: 'MENU_EVENTS.HELP',
	LOAD: 'MENU_EVENTS.LOAD',
	EXPORT: 'MENU_EVENTS.EXPORT',
	GRID: 'MENU_EVENTS.GRID',
	CLEAR: 'MENU_EVENTS.CLEAR',
	TOGGLE_APP_MENUBAR: 'MENU_EVENTS.TOGGLE_APP_MENUBAR',
};
