export const MENU_EVENTS = {
	HELP: 'MENU_EVENTS.HELP',
	LOAD: 'MENU_EVENTS.LOAD',
	EXPORT: 'MENU_EVENTS.EXPORT',
	GRID: 'MENU_EVENTS.GRID',
	CLEAR: 'MENU_EVENTS.CLEAR',
	TOGGLE_APP_MENUBAR: 'MENU_EVENTS.TOGGLE_APP_MENUBAR',
	REQUEST_SAVE_ALIGNMENT: 'MENU_EVENTS.REQUEST_SAVE',
	REQUEST_DELETE_ALIGNMENT: 'MENU_EVENTS.REQUEST_DELETE',
	REQUEST_LOAD_ALIGNMENT: 'MENU_EVENTS.REQUEST_LOAD',
	REQUEST_LOAD_ALIGNMENT_COMPLETE: 'MENU_EVENTS.REQUEST_LOAD_COMPLETE',
};
