export const PREVIEW_EVENTS = {
	UPDATE_ZOOM: 'PREVIEW_EVENTS.UPDATE_ZOOM',
	UPDATE_PAN: 'PREVIEW_EVENTS.UPDATE_PAN',
	START_WINDOW_ANIMATION: 'PREVIEW_EVENTS.START_WINDOW_ANIMATION',
	STOP_WINDOW_ANIMATION: 'PREVIEW_EVENTS.STOP_WINDOW_ANIMATION',
};
