export const PREVIEW_EVENTS = {
	UPDATE_ZOOM: 'PREVIEW_EVENTS.UPDATE_ZOOM',
	UPDATE_PAN: 'PREVIEW_EVENTS.UPDATE_PAN',
	START_WINDOW_ANIMATION: 'PREVIEW_EVENTS.START_WINDOW_ANIMATION',
	STOP_WINDOW_ANIMATION: 'PREVIEW_EVENTS.STOP_WINDOW_ANIMATION',
	REQUEST_SAVE: 'PREVIEW_EVENTS.REQUEST_SAVE',
	REQUEST_DELETE: 'PREVIEW_EVENTS.REQUEST_DELETE',
	REQUEST_LOAD: 'PREVIEW_EVENTS.REQUEST_LOAD',
	REQUEST_LOAD_COMPLETE: 'PREVIEW_EVENTS.REQUEST_LOAD_COMPLETE',
	UPDATE_SETTINGS: 'PREVIEW_EVENTS.UPDATE_SETTINGS',
};
