export const SETTINGS_EVENTS = {
	UPDATE: 'SETTINGS_EVENTS.UPDATE',
	REQUEST_SAVE: 'SETTINGS_EVENTS.REQUEST_SAVE',
	REQUEST_DELETE: 'SETTINGS_EVENTS.REQUEST_DELETE',
	REQUEST_LOAD: 'SETTINGS_EVENTS.REQUEST_LOAD',
	REQUEST_LOAD_COMPLETE: 'SETTINGS_EVENTS.REQUEST_LOAD_COMPLETE',
};
