/**
 * Args for UPLOADER_EVENTS.IMAGE_LOADED  
 * @typedef {{image: HTMLImageElement, src: string, isRender?: boolean}} ImageLoadedData
 */

export const UPLOADER_EVENTS = {
	OPEN: 'UPLOADER_EVENTS.OPEN',
	PRELOAD: 'UPLOADER_EVENTS.PRELOAD',
	READY: 'UPLOADER_EVENTS.READY',
	IMAGE_LOADED: 'UPLOADER_EVENTS.IMAGE_LOADED',
	UPDATE_IMAGE: 'UPLOADER_EVENTS.UPDATE_IMAGE'
}; 
