/**
 * Args for GRID_EVENTS.CREATE
 * @typedef {{cachedImage: HTMLImageElement}} CreateViewportData
 */

export const VIEWPORT_EVENTS = {
	UPDATE_ZOOM: 'VIEWPORT_EVENTS.UPDATE_ZOOM',
	UPDATE_PAN: 'VIEWPORT_EVENTS.UPDATE_PAN',
	CREATED: 'VIEWPORT_EVENTS.CREATED',
	DESTROY: 'VIEWPORT_EVENTS.DESTROY',
};
